/**
 * Constants for Northwind App Tests
 */

export enum PreviewControls {
  BlankFlexibleHeightGallery = 'Blank flexible height gallery',
  BlankVerticalGallery = 'Blank vertical gallery',
  Button = 'Button',
  Checkbox = 'Check box',
  ComboBox = 'Combo box',
  DataTable = 'Data table',
  DatePicker = 'Date picker',
  Dropdown = 'Drop down',
  EditForm = 'Edit form',
  Radio = 'Radio',
  Slider = 'Slider',
  Toggle = 'Toggle',
  TextLabel = 'Text label',
  TextInput = 'Text input',
}

export enum Buttons {
  Actions = 'Actions',
  AddMedia = 'Add media',
  AdvancedTools = 'Advanced tools',
  All = 'All',
  Allow = 'Allow',
  Apply = 'Apply',
  Cancel = 'Cancel',
  Connect = 'Connect',
  Data = 'Data',
  Details = 'Details',
  Edit = 'Edit',
  Errors = 'Errors',
  Formulas = 'Formulas',
  FromFile = 'From file (.msapp, .pa.yaml)',
  FromPackage = 'From package (.zip)',
  Gallery = 'Gallery',
  Glyphs = 'Glyphs',
  ImportApp = 'Import app',
  Insert = 'Insert',
  List = 'List',
  Media = 'Media',
  Navigation = 'Navigation',
  Objects = 'Objects',
  PowerAutomate = 'Power Automate',
  ReplaceColumns = 'Replace columns',
  Save = 'Save',
  Search = 'Search',
  SignIn = 'Sign in',
  Themes = 'Themes',
  TreeView = 'Tree view',
  Variables = 'Variables',
  ViewAll = 'View all',
}

export enum KeyboardAction {
  Alt = 'Alt',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  ArrowUp = 'ArrowUp',
  Bold = 'Control+B',
  Copy = 'Control+C',
  Cut = 'Control+X',
  Delete = 'Delete',
  Enter = 'Enter',
  Escape = 'Escape',
  Group = 'Control+G',
  Home = 'Home',
  Italic = 'Control+I',
  Paste = 'Control+V',
  SelectAll = 'Control+A',
  Shift = 'Shift',
  ShiftArrowRight = 'Shift+ArrowRight',
  ShiftLeft = 'ShiftLeft',
  Tab = 'Tab',
  Underline = 'Control+U',
  UnGroup = 'Control+Shift+G',
}
